# Generated by Django 4.1.2 on 2023-02-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_add_files_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_files',
            name='img_number',
            field=models.IntegerField(null=True),
        ),
    ]
