# Generated by Django 4.1.2 on 2023-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_add_files_img_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_list',
            name='city',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='contact_list',
            name='contact_number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='contact_list',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_list',
            name='category',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_list',
            name='contact_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
