# Generated by Django 4.1.2 on 2023-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contct_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
