# Generated by Django 4.1.2 on 2023-02-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_list',
            old_name='contct_name',
            new_name='contact_name',
        ),
    ]
